# Generated by Django 4.0.4 on 2022-05-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='media/articles/default.jpg', upload_to='articles/'),
        ),
    ]
